color_roi_node:
  ros__parameters:
    image_topic: "/camera/color/image_raw"
    roi_x: 440
    roi_y: 50
    roi_w: 500
    roi_h: 250
    min_ratio: 0.02
    blur_kernel: 5

    colors:
      red:
        - lower: [0, 120, 100]
          upper: [10, 255, 255]
        - lower: [170, 120, 100]
          upper: [180, 255, 255]
      
      orange:
        - lower: [8, 150, 120]
          upper: [20, 255, 255]
      
      yellow:
        - lower: [20, 100, 120]
          upper: [35, 255, 255]
      
      green:
        - lower: [40, 80, 80]
          upper: [85, 255, 255]
      
      blue:
        - lower: [85, 100, 100]
          upper: [130, 255, 255]